/* FLAIR MASTER CONFIG | auto-generated at 2017-12-01T11:35:10-0800 (ISO-8601) */
flair.load__by_id = function () {
	for (var key in flair.names) {
		if (flair.names.hasOwnProperty(key)) {
			var data = key.split(' ');

			var orig_id = data[2];

			if (orig_id.substring(0, 'a'.length) === 'a') {
				orig_id = orig_id.substring(1);
			}
			if (orig_id.substring(orig_id.length - 'm'.length) === 'm') {
				orig_id = orig_id.substring(0, orig_id.length - 1);
			}
			if (orig_id.substring(orig_id.length - 'o'.length) === 'o') {
				orig_id = orig_id.substring(0, orig_id.length - 1);
			}
			if (orig_id.substring(orig_id.length - 'x'.length) === 'x') {
				orig_id = orig_id.substring(0, orig_id.length - 1);
			}
			if (orig_id.substring(orig_id.length - 'y'.length) === 'y') {
				orig_id = orig_id.substring(0, orig_id.length - 1);
			}
			if (orig_id.substring(orig_id.length - 1).match(/[a-z]/i) &&
				orig_id.substring(0, orig_id.length - 1).match(/^\d+$/)) {
				orig_id = orig_id.substring(0, orig_id.length - 1);
			}

			var flair_class = '';
			for (var i = 0; i < data.length; i++) {
				flair_class += 'flair-' + data[i] + ' ';
			}

			flair_class = flair_class.slice(0, -1);


			flair.by_id[data[2]] = {
				key: key,
				heropos: data[0],
				sheet: data[1],
				hero_id: data[2],
				orig_id: orig_id,
				hero_name: flair.names[key],
				flair_class: flair_class,
			}
		}
	}
};
flair.by_id = {};
flair.names = {
	/* [STANDARD] */

    

"abomination tierlist abomination": "Abomination [Modern] #L##T##D##PVE##PVP# ",
"absorbingman tierlist absorbingman": "Absorbing Man [Modern]  ",
"adamwarlock tierlist adamwarlock": "Adam Warlock [Modern]  ",
"aero tierlist aero": "Aero [Modern]  ",
"agent13 tierlist agent13": "Agent 13 [Modern]  ",
"agentvenom tierlist agentvenom": "Agent Venom [All-New, All-Different]  ",
"americachavez tierlist americachavez": "America Chavez [Ultimates]  ",
"ancientone tierlist ancientone": "Ancient One [Modern]  ",
"angel tierlist angel": "Angel [Classic]  ",
"angela tierlist angela": "Angela [Modern]  ",
"anti-man tierlist anti-man": "Anti-Man [All-New, All-Different]  ",
"ant-man tierlist ant-man": "Ant-Man [Modern]  ",
"apocalypse tierlist apocalypse": "Apocalypse [Messiah Complex] #D##PVE##Cry##E##Rage#",
"arachknight tierlist arachknight": "Arachknight [Infinity Warps]  ",
"ares tierlist ares": "Ares [Modern] #L##D##PVE##Rage#",
"baronmordo tierlist baronmordo": "Baron Mordo [Classic]  ",
"baronzemo tierlist baronzemo": "Baron Zemo [Modern]  ",
"beast tierlist beast": "Beast [Classic]  ",
"betaraybill tierlist betaraybill": "Beta Ray Bill [Modern]  ",
"bishop tierlist bishop": "Bishop [Disassembled]  ",
"blackbolt tierlist blackbolt": "Black Bolt [Modern]  ",
"blackcat tierlist blackcat": "Black Cat [Modern]  ",
"blackdwarf tierlist blackdwarf": "Black Dwarf [Infinity]  ",
"blackpanther tierlist blackpanther": "Black Panther [Modern]  ",
"blackwidow tierlist blackwidow": "Black Widow [The Avengers]  ",
"blade tierlist blade": "Blade [Modern]  ",
"bluedragon tierlist bluedragon": "Blue Dragon [Modern]  ",
"bluemarvel tierlist bluemarvel": "Blue Marvel [Ultimates]  ",
"bullseye tierlist bullseye": "Bullseye [Modern]  ",
"cable tierlist cable": "Cable [Modern]  ",
"captainamerica tierlist captainamerica": "Captain America [The Avengers]  ",
"captainamericasharonrogers tierlist captainamericasharonrogers": "Captain America Sharon Rogers [Captain America 75th Anniversary]  ",
"captainmarvel tierlist captainmarvel": "Captain Marvel [Modern]  ",
"carnage tierlist carnage": "Carnage [Absolute Carnage] #D##PVE##P##Rage#",
"clea tierlist clea": "Clea [Modern]  ",
"colossus tierlist colossus": "Colossus [Phoenix Five] #T##PVE##Insight#",
"corvusglaive tierlist corvusglaive": "Corvus Glaive [Infinity]  ",
"crescent tierlist crescent": "Crescent [Modern]  ",
"crossbones tierlist crossbones": "Crossbones [Captain America: Civil War]  ",
"crystal tierlist crystal": "Crystal [All-New, All-Different]  ",
"cyclops tierlist cyclops": "Cyclops [Classic]  ",
"daisyjohnson tierlist daisyjohnson": "Daisy Johnson [Marvel's Agents of S.H.I.E.L.D.]  ",
"daken tierlist daken": "Daken [Modern]  ",
"daredevil tierlist daredevil": "Daredevil [Modern]  ",
"darkhawk tierlist darkhawk": "Darkhawk [Modern]  ",
"dazzler tierlist dazzler": "Dazzler [Modern]  ",
"deadpool tierlist deadpool": "Deadpool [Modern]  ",
"deathlok tierlist deathlok": "Deathlok [Marvel's Agents of S.H.I.E.L.D.]  ",
"destroyer tierlist destroyer": "Destroyer [Classic]  ",
"doctordoom tierlist doctordoom": "Doctor Doom [Modern]  ",
"doctoroctopus tierlist doctoroctopus": "Doctor Octopus [Classic]  ",
"doctorstrange tierlist doctorstrange": "Doctor Strange [All-New, All-Different]  ",
"doctorvoodoo tierlist doctorvoodoo": "Doctor Voodoo [Modern]  ",
"domino tierlist domino": "Domino [X-Force]  ",
"dormammu tierlist dormammu": "Dormammu [Classic]  ",
"drax tierlist drax": "Drax [Guardians of the Galaxy]  ",
"ebonymaw tierlist ebonymaw": "Ebony Maw [Infinity]  ",
"electro tierlist electro": "Electro [Modern]  ",
"elektra tierlist elektra": "Elektra [Classic]  ",
"elsabloodstone tierlist elsabloodstone": "Elsa Bloodstone [Modern]  ",
"emmafrost tierlist emmafrost": "Emma Frost [Modern]  ",
"enchantress tierlist enchantress": "Enchantress [Modern]  ",
"falcon tierlist falcon": "Falcon [Captain America: The Winter Soldier]  ",
"fandral tierlist fandral": "Fandral [Modern]  ",
"fantomex tierlist fantomex": "Fantomex [X-Force]  ",
"gambit tierlist gambit": "Gambit [Modern]  ",
"gamora tierlist gamora": "Gamora [Guardians of the Galaxy]  ",
"ghost tierlist ghost": "Ghost [Modern]  ",
"ghostpanther tierlist ghostpanther": "Ghost Panther [Infinity Warps]  ",
"ghostrider tierlist ghostrider": "Ghost Rider [Classic]  ",
"ghostriderrobbiereyes tierlist ghostriderrobbiereyes": "Ghost Rider Robbie Reyes [Marvel NOW!]  ",
"giant-man tierlist giant-man": "Giant-Man [Modern]  ",
"gladiator tierlist gladiator": "Gladiator [Modern] #L##D##PVE##Cry##E##Rage#",
"goliath tierlist goliath": "Goliath [Classic]  ",
"gorgon tierlist gorgon": "Gorgon [War of Kings]  ",
"gorilla-man tierlist gorilla-man": "Gorilla-Man [Modern]  ",
"greengoblin tierlist greengoblin": "Green Goblin [Classic]  ",
"groot tierlist groot": "Groot [Guardians of the Galaxy]  ",
"gwenpool tierlist gwenpool": "Gwenpool [All-New, All-Different]  ",
"hawkeye tierlist hawkeye": "Hawkeye [The Avengers]  ",
"hawkeyekatebishop tierlist hawkeyekatebishop": "Hawkeye Kate Bishop [Marvel NOW!]  ",
"heimdall tierlist heimdall": "Heimdall [Marvel's Thor: Ragnarok]  ",
"hela tierlist hela": "Hela [Modern]  ",
"hellcat tierlist hellcat": "Hellcat [All-New, All-Different]  ",
"hellstorm tierlist hellstorm": "Hellstorm [Modern]  ",
"hogun tierlist hogun": "Hogun [Modern]  ",
"hulk tierlist hulk": "Hulk [Immortal] #D##PVP##Rage#",
"hulkamadeuscho tierlist hulkamadeuscho": "Hulk Amadeus Cho [Totally Awesome Hulk] #D##PVE##Rage#",
"hulkbuster tierlist hulkbuster": "Hulkbuster [Avengers: Age of Ultron]  ",
"hulkling tierlist hulkling": "Hulkling [New Avengers]  ",
"humantorch tierlist humantorch": "Human Torch [Modern]  ",
"hydro-man tierlist hydro-man": "Hydro-Man [Spider-Man: Far From Home]  ",
"hyperion tierlist hyperion": "Hyperion [All-New, All-Different]  ",
"iceman tierlist iceman": "Iceman [Modern]  ",
"inferno tierlist inferno": "Inferno [All-New, All-Different]  ",
"invisiblewoman tierlist invisiblewoman": "Invisible Woman [Modern]  ",
"ironfist tierlist ironfist": "Iron Fist [The Living Weapon] #D##PVE##Energy#",
"ironhammer tierlist ironhammer": "Iron Hammer [Infinity Warps]  ",
"ironheart tierlist ironheart": "Ironheart [Marvel NOW!]  ",
"ironman tierlist ironman": "Iron Man [The Avengers]  ",
"jeangrey tierlist jeangrey": "Jean Grey [Phoenix]  ",
"jessicajones tierlist jessicajones": "Jessica Jones [Jewel] #T##D##PVE##Transcendence#",
"jocasta tierlist jocasta": "Jocasta [Jocasta]  ",
"jubilee tierlist jubilee": "Jubilee [Classic]  ",
"juggernaut tierlist juggernaut": "Juggernaut [Brotherhood of Mutants]  ",
"kaecilius tierlist kaecilius": "Kaecilius [Marvel's Doctor Strange]  ",
"karnak tierlist karnak": "Karnak [War of Kings]  ",
"kidkaiju tierlist kidkaiju": "Kid Kaiju [Monsters Unleashed!]  ",
"kidomega tierlist kidomega": "Kid Omega [Modern]  ",
"killmonger tierlist killmonger": "Killmonger [Classic]  ",
"kingpin tierlist kingpin": "Kingpin [Modern]  ",
"kittypryde tierlist kittypryde": "Kitty Pryde [Modern]  ",
"knull tierlist knull": "Knull [Modern]  ",
"korath tierlist korath": "Korath [Captain Marvel]  ",
"kraventhehunter tierlist kraventhehunter": "Kraven The Hunter [Modern]  ",
"lash tierlist lash": "Lash [Marvel's Agents of S.H.I.E.L.D.]  ",
"lincoln tierlist lincoln": "Lincoln [Marvel's Agents of S.H.I.E.L.D.]  ",
"lizard tierlist lizard": "Lizard [Classic]  ",
"loki tierlist loki": "Loki [The Avengers]  ",
"lukecage tierlist lukecage": "Luke Cage [Uptown Suit] #D##PVP##Regen#",
"lunasnow tierlist lunasnow": "Luna Snow [Modern]  ",
"modok tierlist modok": "Modok [Classic]  ",
"magik tierlist magik": "Magik [Modern]  ",
"magneto tierlist magneto": "Magneto [Classic]  ",
"malekith tierlist malekith": "Malekith [Thor: The Dark World]  ",
"mantis tierlist mantis": "Mantis [Guardians of the Galaxy 2]  ",
"maximus tierlist maximus": "Maximus [War of Kings]  ",
"medusa tierlist medusa": "Medusa [All-New, All-Different]  ",
"minn-erva tierlist minn-erva": "Minn-Erva [Modern]  ",
"misterfantastic tierlist misterfantastic": "Mister Fantastic [The Maker] #L##D##PVE##Rage#",
"mistersinister tierlist mistersinister": "Mister Sinister [Modern]  ",
"mistyknight tierlist mistyknight": "Misty Knight [All-New, All-Different]  ",
"mockingbird tierlist mockingbird": "Mockingbird [Heroic Age]  ",
"moleculeman tierlist moleculeman": "Molecule Man [Modern]  ",
"moltenman tierlist moltenman": "Molten Man [Spider-Man: Far From Home]  ",
"moongirl tierlist moongirl": "Moon Girl [Marvel NOW!]  ",
"moonknight tierlist moonknight": "Moon Knight [Mr. Knight] #D##PVE##Energy#",
"moonstone tierlist moonstone": "Moonstone [Dark Avengers]  ",
"morbius tierlist morbius": "Morbius [Modern]  ",
"morganlefay tierlist morganlefay": "Morgan Le Fay [Modern]  ",
"ms.marvelkamalakhan tierlist ms.marvelkamalakhan": "Ms. Marvel Kamala Khan [All-New, All-Different]  ",
"mysterio tierlist mysterio": "Mysterio [Classic]  ",
"mystique tierlist mystique": "Mystique [Modern]  ",
"namor tierlist namor": "Namor [Phoenix Five] #D##PVE##P##Rage#",
"nebula tierlist nebula": "Nebula [Guardians of the Galaxy]  ",
"negasonicteenagewarhead tierlist negasonicteenagewarhead": "Negasonic Teenage Warhead [Modern]  ",
"nickfury tierlist nickfury": "Nick Fury [Modern]  ",
"nightcrawler tierlist nightcrawler": "Nightcrawler [Modern]  ",
"odin tierlist odin": "Odin [Modern]  ",
"philcoulson tierlist philcoulson": "Phil Coulson [Marvel's Agents of S.H.I.E.L.D.]  ",
"phyla-vell tierlist phyla-vell": "Phyla-Vell [Modern]  ",
"professorx tierlist professorx": "Professor X [Modern]  ",
"proximamidnight tierlist proximamidnight": "Proxima Midnight [Infinity]  ",
"psylocke tierlist psylocke": "Psylocke [X-Force]  ",
"punisher tierlist punisher": "Punisher [Modern]  ",
"quasaravrilkincaid tierlist quasaravrilkincaid": "Quasar Avril Kincaid [All-New, All-Different]  ",
"quicksilver tierlist quicksilver": "Quicksilver [Classic]  ",
"rachelsummers tierlist rachelsummers": "Rachel Summers [Modern]  ",
"redguardian tierlist redguardian": "Red Guardian [Modern]  ",
"redhulk tierlist redhulk": "Red Hulk [Modern]  ",
"redshe-hulk tierlist redshe-hulk": "Red She-Hulk [Modern]  ",
"redskull tierlist redskull": "Red Skull [Captain America: The First Avenger]  ",
"rescue tierlist rescue": "Rescue [Marvel's Avengers: Endgame]  ",
"rhino tierlist rhino": "Rhino [Classic]  ",
"novarichardrider tierlist novarichardrider": "Nova Richard Rider [Modern]  ",
"rocketraccoon tierlist rocketraccoon": "Rocket Raccoon [Guardians of the Galaxy]  ",
"rogue tierlist rogue": "Rogue [Classic]  ",
"ronan tierlist ronan": "Ronan [Guardians of the Galaxy]  ",
"sabretooth tierlist sabretooth": "Sabretooth [Brotherhood of Mutants]  ",
"sandman tierlist sandman": "Sandman [Classic]  ",
"novasamalexander tierlist novasamalexander": "Nova Sam Alexander [All-New, All-Different]  ",
"satana tierlist satana": "Satana [Modern]  ",
"scarletspider tierlist scarletspider": "Scarlet Spider [Modern]  ",
"scarletwitch tierlist scarletwitch": "Scarlet Witch [Classic]  ",
"scorpion tierlist scorpion": "Scorpion [Modern]  ",
"scream tierlist scream": "Scream [Modern]  ",
"sentinel tierlist sentinel": "Sentinel [Modern]  ",
"sentry tierlist sentry": "Sentry [Modern]  ",
"shadowshell tierlist shadowshell": "Shadow Shell [Modern]  ",
"shangchi tierlist shangchi": "Shang Chi [Modern]  ",
"she-hulk tierlist she-hulk": "She-Hulk [Avengers] #T##PVE##Insight#",
"shuri tierlist shuri": "Shuri [Marvel Legacy]  ",
"sif tierlist sif": "Sif [Marvel's Agents of S.H.I.E.L.D.]  ",
"silk tierlist silk": "Silk [All-New, All-Different]  ",
"silversurfer tierlist silversurfer": "Silver Surfer [Modern]  ",
"sin tierlist sin": "Sin [All-New, All-Different]  ",
"singularity tierlist singularity": "Singularity [Secret Wars: A-Force]  ",
"sistergrimm tierlist sistergrimm": "Sister Grimm [Secret Wars: A-Force]  ",
"skurge tierlist skurge": "Skurge [Marvel's Thor: Ragnarok]  ",
"slapstick tierlist slapstick": "Slapstick [Modern]  ",
"songbird tierlist songbird": "Songbird [New Avengers]  ",
"spider-gwen tierlist spider-gwen": "Spider-Gwen [All-New, All-Different]  ",
"spider-man tierlist spider-man": "Spider-Man [Classic]  ",
"spider-man2099 tierlist spider-man2099": "Spider-Man 2099 [Modern]  ",
"spider-manmilesmorales tierlist spider-manmilesmorales": "Spider-Man Miles Morales [All-New, All-Different]  ",
"spider-woman tierlist spider-woman": "Spider-Woman [Modern]  ",
"squirrelgirl tierlist squirrelgirl": "Squirrel Girl [New Avengers]  ",
"star-lord tierlist star-lord": "Star-Lord [Guardians of the Galaxy]  ",
"storm tierlist storm": "Storm [Modern]  ",
"stryfe tierlist stryfe": "Stryfe [Modern]  ",
"sunbird tierlist sunbird": "Sun Bird [Modern]  ",
"supergiant tierlist supergiant": "Supergiant [Infinity]  ",
"swordmaster tierlist swordmaster": "Sword Master [Modern]  ",
"taskmaster tierlist taskmaster": "Taskmaster [Black Widow] #T##PVE##Insight#",
"thane tierlist thane": "Thane [Modern]  ",
"thanos tierlist thanos": "Thanos [Infinity]  ",
"thething tierlist thething": "The Thing [Modern] #T##D##PVE##Insight#",
"thor tierlist thor": "Thor [The Avengers]  ",
"thorjanefoster tierlist thorjanefoster": "Thor Jane Foster [All-New, All-Different]  ",
"titania tierlist titania": "Titania [Modern]  ",
"ulik tierlist ulik": "Ulik [Modern]  ",
"ultron tierlist ultron": "Ultron [Modern]  ",
"ulyssesklaue tierlist ulyssesklaue": "Ulysses Klaue [Marvel's Black Panther]  ",
"valkyrie tierlist valkyrie": "Valkyrie [Fearless Defenders] #T##PVE##P##Insight#",
"venom tierlist venom": "Venom [War of the Realms] #T##D##PVE##Rage#",
"victorious tierlist victorious": "Victorious [Modern]  ",
"viper tierlist viper": "Viper [Modern]  ",
"vision tierlist vision": "Vision [Modern]  ",
"volstagg tierlist volstagg": "Volstagg [Modern]  ",
"vulture tierlist vulture": "Vulture [Classic]  ",
"warmachine tierlist warmachine": "War Machine [Modern]  ",
"wartiger tierlist wartiger": "War Tiger [Modern]  ",
"warpath tierlist warpath": "Warpath [X-Force]  ",
"warwolf tierlist warwolf": "Warwolf [The Howling Commandos of S.H.I.E.L.D.]  ",
"wasp tierlist wasp": "Wasp [Modern]  ",
"waspnadiavandyne tierlist waspnadiavandyne": "Wasp Nadia Van Dyne [Modern]  ",
"wave tierlist wave": "Wave [Modern]  ",
"weaponhex tierlist weaponhex": "Weapon Hex [Infinity Warps]  ",
"whiplash tierlist whiplash": "Whiplash [Marvel's Iron Man 2]  ",
"whitefox tierlist whitefox": "White Fox [Modern]  ",
"whitetiger tierlist whitetiger": "White Tiger [New Avengers]  ",
"wiccan tierlist wiccan": "Wiccan [New Avengers]  ",
"wintersoldier tierlist wintersoldier": "Winter Soldier [Captain America: The Winter Soldier]  ",
"wolverine tierlist wolverine": "Wolverine [Classic]  ",
"wong tierlist wong": "Wong [All-New, All-Different]  ",
"x-23 tierlist x-23": "X-23 [All-New Wolverine] #D##PVE##Cra##Rage#",
"yelenabelova tierlist yelenabelova": "Yelena Belova [Modern]  ",
"yellowjacket tierlist yellowjacket": "Yellowjacket [Marvel's Ant-Man]  ",
"yondu tierlist yondu": "Yondu [Guardians of the Galaxy]  ",


};
