/* FLAIR MASTER CONFIG | auto-generated at 2017-12-01T11:35:10-0800 (ISO-8601) */
flair.load__by_id = function () {
	for (var key in flair.names) {
		if (flair.names.hasOwnProperty(key)) {
			var data = key.split(' ');

			var orig_id = data[2];

			if (orig_id.substring(0, 'a'.length) === 'a') {
				orig_id = orig_id.substring(1);
			}
			if (orig_id.substring(orig_id.length - 'm'.length) === 'm') {
				orig_id = orig_id.substring(0, orig_id.length - 1);
			}
			if (orig_id.substring(orig_id.length - 'o'.length) === 'o') {
				orig_id = orig_id.substring(0, orig_id.length - 1);
			}
			if (orig_id.substring(orig_id.length - 'x'.length) === 'x') {
				orig_id = orig_id.substring(0, orig_id.length - 1);
			}
			if (orig_id.substring(orig_id.length - 'y'.length) === 'y') {
				orig_id = orig_id.substring(0, orig_id.length - 1);
			}
			if (orig_id.substring(orig_id.length - 1).match(/[a-z]/i) &&
				orig_id.substring(0, orig_id.length - 1).match(/^\d+$/)) {
				orig_id = orig_id.substring(0, orig_id.length - 1);
			}

			var flair_class = '';
			for (var i = 0; i < data.length; i++) {
				flair_class += 'flair-' + data[i] + ' ';
			}

			flair_class = flair_class.slice(0, -1);


			flair.by_id[data[2]] = {
				key: key,
				heropos: data[0],
				sheet: data[1],
				hero_id: data[2],
				orig_id: orig_id,
				hero_name: flair.names[key],
				flair_class: flair_class,
			}
		}
	}
};
flair.by_id = {};
flair.names = {
	/* [STANDARD] */

"abomination tierlist abomination": "Abomination [Modern] #L##S##D##PVE##Cry##Energy#",
"absorbingman tierlist absorbingman": "Absorbing Man [Modern] #PVE# ",
"adamwarlock tierlist adamwarlock": "Adam Warlock [Modern] #PVE##Cry##E# ",
"aero tierlist aero": "Aero [Modern] #PVE##P# ",
"agent13 tierlist agent13": "Agent 13 [Captain America: Civil War] #PVE# ",
"agentvenom tierlist agentvenom": "Agent Venom [Agent Anti-Venom] #PVE##P# ",
"americachavez tierlist americachavez": "America Chavez [Ultimates] #L##PVE# ",
"ancientone tierlist ancientone": "Ancient One [Doctor Strange] #L##S##PVE# ",
"angel tierlist angel": "Angel [X-Force] #L##PVE# ",
"angela tierlist angela": "Angela [All-New, All-Different] #PVE# ",
"anti-man tierlist anti-man": "Anti-Man [All-New, All-Different] #L##PVP##Cra##Rage#",
"ant-man tierlist ant-man": "Ant-Man [Avengers: Endgame (Team Suit)] #PVE##PVP##Rage#",
"apocalypse tierlist apocalypse": "Apocalypse [Messiah Complex] #D##PVE##Cry##E##Rage#",
"arachknight tierlist arachknight": "Arachknight [Infinity Warps] #PVP##Cry# ",
"ares tierlist ares": "Ares [Modern] #L##D##PVE##Rage#",
"baronmordo tierlist baronmordo": "Baron Mordo [Doctor Strange] #PVE# ",
"baronzemo tierlist baronzemo": "Baron Zemo [Modern] #L##PVE##P##Insight#",
"beast tierlist beast": "Beast [Uncanny X-Men] #L##S##PVE# ",
"betaraybill tierlist betaraybill": "Beta Ray Bill [Modern] #L##D##PVE##C##Energy#",
"bishop tierlist bishop": "Bishop [Disassembled] #PVE# ",
"blackbolt tierlist blackbolt": "Black Bolt [Marvels X] #D##PVE##Rage#",
"blackcat tierlist blackcat": "Black Cat [All-New, All-Different] #S##PVE# ",
"blackdwarf tierlist blackdwarf": "Black Dwarf [Dark Obsidian Armor] #PVE##C# ",
"blackpanther tierlist blackpanther": "Black Panther [Black Panther] #PVE##Rage#",
"blackwidow tierlist blackwidow": "Black Widow [Black Widow] #D##PVE##PVP##Rage#",
"blade tierlist blade": "Blade [Avengers] #D##PVE##Transcendence#",
"bluedragon tierlist bluedragon": "Blue Dragon [Modern] #L##D##PVE##PVP##Cry##Rage#",
"bluemarvel tierlist bluemarvel": "Blue Marvel [Ultimates] #PVP##Cra# ",
"bullseye tierlist bullseye": "Bullseye [Dark Avengers] #L##D##PVE##Rage#",
"cable tierlist cable": "Cable [X of Swords] #L##D##PVE##C##Rage#",
"captainamerica tierlist captainamerica": "Captain America [Hydra Supreme] #D##PVE##Rage#",
"captainamericasharonrogers tierlist captainamericasharonrogers": "Captain America Sharon Rogers [Star Night Armor] #D##PVE##Energy#",
"captainmarvel tierlist captainmarvel": "Captain Marvel [Avengers: Endgame] #L##D##PVP##Rage#",
"carnage tierlist carnage": "Carnage [Absolute Carnage] #D##PVE##P##Rage#",
"clea tierlist clea": "Clea [Modern] #PVE# ",
"colossus tierlist colossus": "Colossus [Phoenix Five] #S##PVE##Insight#",
"corvusglaive tierlist corvusglaive": "Corvus Glaive [Dark Obsidian Armor] #PVP##C# ",
"crescent tierlist crescent": "Crescent [Lifestyle Series 1] #L##D##PVE##P##Rage#",
"crossbones tierlist crossbones": "Crossbones [Secret Empire] #D##PVE# ",
"crystal tierlist crystal": "Crystal [Fantastic Four] #PVE# ",
"cyclops tierlist cyclops": "Cyclops [Phoenix Five] #L##S##D##PVE##Rage#",
"daisyjohnson tierlist daisyjohnson": "Daisy Johnson [ Agents of S.H.I.E.L.D. (Quake)] #PVE# ",
"daken tierlist daken": "Daken [Modern] #D##PVE# ",
"daredevil tierlist daredevil": "Daredevil [Fall From Grace] #D##PVE##Energy#",
"darkhawk tierlist darkhawk": "Darkhawk [Modern] #PVE##Rage#",
"dazzler tierlist dazzler": "Dazzler [Modern] #S##D##PVE##P# ",
"deadpool tierlist deadpool": "Deadpool [30th Anniversary Black Version] #D##PVE##PVP##C##Energy#",
"deathlok tierlist deathlok": "Deathlok [Modern] #PVE# ",
"destroyer tierlist destroyer": "Destroyer [Prometheus] #PVP##Regen#",
"doctordoom tierlist doctordoom": "Doctor Doom [Modern] #L##D##PVP##Cry##E##Rage#",
"doctoroctopus tierlist doctoroctopus": "Doctor Octopus [Superior Octopus] #D##PVE##Rage#",
"doctorstrange tierlist doctorstrange": "Doctor Strange [Space Suit] #L##S##D##PVE##C##Rage#",
"doctorvoodoo tierlist doctorvoodoo": "Doctor Voodoo [Modern] #L##PVE##Rage#",
"domino tierlist domino": "Domino [Marvel NOW!] #L##PVE# ",
"dormammu tierlist dormammu": "Dormammu [Damnation] #D##PVE##E##Judgement#",
"drax tierlist drax": "Drax [All-New, All-Different] #PVE# ",
"ebonymaw tierlist ebonymaw": "Ebony Maw [Dark Obsidian Armor] #L##S##PVE##C# ",
"electro tierlist electro": "Electro [Modern] #L##PVE##P# ",
"elektra tierlist elektra": "Elektra [Daredevil] #PVE# ",
"elsabloodstone tierlist elsabloodstone": "Elsa Bloodstone [Monsters Unleashed!] #PVE# ",
"emmafrost tierlist emmafrost": "Emma Frost [Phoenix Five] #PVE# ",
"enchantress tierlist enchantress": "Enchantress [Summer Days] #S##PVE##P# ",
"falcon tierlist falcon": "Falcon [Marvel Legacy] #PVE# ",
"fandral tierlist fandral": "Fandral [Modern] #PVE# ",
"fantomex tierlist fantomex": "Fantomex [X-Force] #PVE# ",
"gambit tierlist gambit": "Gambit [Excalibur] #L##D##PVE##P##Energy#",
"gamora tierlist gamora": "Gamora [Guardians of the Galaxy 2] #PVE# ",
"ghost tierlist ghost": "Ghost [Ant-Man and the Wasp] #L##S##PVE##P# ",
"ghostpanther tierlist ghostpanther": "Ghost Panther [Infinity Warps] #L##S##PVE##P##Insight#",
"ghostrider tierlist ghostrider": "Ghost Rider [King of Hell] #D##PVE##Rage#",
"ghostriderrobbiereyes tierlist ghostriderrobbiereyes": "Ghost Rider Robbie Reyes [Marvel NOW!] #L##PVE# ",
"giant-man tierlist giant-man": "Giant-Man [Ultron Pym] #PVE# ",
"gladiator tierlist gladiator": "Gladiator [Modern] #L##D##PVE##Cry##E##Rage#",
"goliath tierlist goliath": "Goliath [Classic] #L##PVE# ",
"gorgon tierlist gorgon": "Gorgon [War of Kings] #L##PVE# ",
"gorilla-man tierlist gorilla-man": "Gorilla-Man [Modern] #PVE# ",
"greengoblin tierlist greengoblin": "Green Goblin [Dark Avengers] #L##D##PVE##Rage#",
"groot tierlist groot": "Groot [Snowflake Festival] #S##PVE# ",
"gwenpool tierlist gwenpool": "Gwenpool [Holiday Party] #D##PVE##Rage#",
"hawkeye tierlist hawkeye": "Hawkeye [Avengers: Endgame] #D##PVE##Rage#",
"hawkeyekatebishop tierlist hawkeyekatebishop": "Hawkeye Kate Bishop [Marvel NOW!] #PVE# ",
"heimdall tierlist heimdall": "Heimdall [Thor: Ragnarok] #PVE# ",
"hela tierlist hela": "Hela [Thor: Ragnarok] #L##S##PVE# ",
"hellcat tierlist hellcat": "Hellcat [All-New, All-Different] #PVE# ",
"hellstorm tierlist hellstorm": "Hellstorm [Modern] #PVE# ",
"hogun tierlist hogun": "Hogun [Modern] #PVE# ",
"hulk tierlist hulk": "Hulk [Immortal Hulk] #D##PVP##Rage#",
"hulkamadeuscho tierlist hulkamadeuscho": "Hulk Amadeus Cho [Brawn] #D##PVE##Rage#",
"hulkbuster tierlist hulkbuster": "Hulkbuster [Avengers: Infinity War] #PVE# ",
"hulkling tierlist hulkling": "Hulkling [New Avengers] #PVE# ",
"humantorch tierlist humantorch": "Human Torch [Classic] #D##PVE##Judgement#",
"hydro-man tierlist hydro-man": "Hydro-Man [Spider-Man: Far From Home] #PVE# ",
"hyperion tierlist hyperion": "Hyperion [Classic] #L##PVE##P# ",
"iceman tierlist iceman": "Iceman [X-Men Blue] #PVE##Cry# ",
"ikaris tierlist ikaris": "Ikaris [Modern] #L##D##PVE##P# ",
"inferno tierlist inferno": "Inferno [Modern] #PVE# ",
"invisiblewoman tierlist invisiblewoman": "Invisible Woman [Classic] #D##PVP##Transcendence#",
"ironfist tierlist ironfist": "Iron Fist [The Living Weapon] #D##PVE##Energy#",
"ironhammer tierlist ironhammer": "Iron Hammer [Infinity Warps] #L##PVE# ",
"ironheart tierlist ironheart": "Ironheart [Marvel NOW!] #L##PVE##P# ",
"ironman tierlist ironman": "Iron Man [Superior Iron Man] #D##PVE##Rage#",
"jeangrey tierlist jeangrey": "Jean Grey [Marvel Girl] #L##D##PVP##Cry##C##Greed#",
"jessicajones tierlist jessicajones": "Jessica Jones [Jewel] #S##D##PVE##Transcendence#",
"jubilee tierlist jubilee": "Jubilee [Classic] #PVE##P# ",
"juggernaut tierlist juggernaut": "Juggernaut [Brotherhood of Mutants] #PVE##P# ",
"kaecilius tierlist kaecilius": "Kaecilius [ Doctor Strange] #PVE# ",
"karnak tierlist karnak": "Karnak [All-New, All-Different] #PVE# ",
"kidkaiju tierlist kidkaiju": "Kid Kaiju [Monsters Unleashed!] #PVE##P# ",
"kidomega tierlist kidomega": "Kid Omega [Modern] #L##D##PVE##Cry##Rage#",
"killmonger tierlist killmonger": "Killmonger [Black Panther] #PVE##P# ",
"kingpin tierlist kingpin": "Kingpin [Secret Wars: Armor Wars] #PVE# ",
"kittypryde tierlist kittypryde": "Kitty Pryde [Modern] #L##PVE##P# ",
"knull tierlist knull": "Knull [Modern] #L##D##PVE##PVP##Lu##Energy#",
"korath tierlist korath": "Korath [Captain Marvel] #PVE# ",
"kraventhehunter tierlist kraventhehunter": "Kraven The Hunter [Modern] #PVE# ",
"lash tierlist lash": "Lash [Modern] #PVE# ",
"lincoln tierlist lincoln": "Lincoln Campbell [ Agents of S.H.I.E.L.D.] #L##PVE# ",
"lizard tierlist lizard": "Lizard [Classic] #PVE# ",
"loki tierlist loki": "Loki [Agent of Asgard] #D##PVE##Rage#",
"lukecage tierlist lukecage": "Luke Cage [Uptown Suit] #D##PVP##Regen#",
"lunasnow tierlist lunasnow": "Luna Snow [Lifestyle Series 1] #D##PVE##P##Rage#",
"magik tierlist magik": "Magik [Phoenix Five] #PVE##P# ",
"magneto tierlist magneto": "Magneto [House of X] #L##D##PVE##Cry##Rage#",
"malekith tierlist malekith": "Malekith [All-New, All-Different] #L##PVE# ",
"mantis tierlist mantis": "Mantis [Guardians of the Galaxy 2] #S##PVE# ",
"maximus tierlist maximus": "Maximus [War of Kings] #PVE# ",
"medusa tierlist medusa": "Medusa [Inhumans vs X-Men] #L##S##D##PVE##Rage#",
"mephisto tierlist mephisto": "Mephisto [Modern] #L##D##PVE##Lu##Judgement#",
"minn-erva tierlist minn-erva": "Minn-Erva [Captain Marvel] #PVE# ",
"misterfantastic tierlist misterfantastic": "Mister Fantastic [The Maker] #L##D##PVE##Rage#",
"mistersinister tierlist mistersinister": "Mister Sinister [Modern] #PVE##P# ",
"mistyknight tierlist mistyknight": "Misty Knight [All-New, All-Different] #L##PVE# ",
"mockingbird tierlist mockingbird": "Mockingbird [All-New, All-Different] #PVE# ",
"modok tierlist modok": "Modok [Capdoc] #PVE# ",
"moleculeman tierlist moleculeman": "Molecule Man [Modern] #L##D##PVE##PVP##Cry##E##Regen#",
"moltenman tierlist moltenman": "Molten Man [Spider-Man: Far From Home] #PVE##Rage#",
"moongirl tierlist moongirl": "Moon Girl [Monsters Unleashed!] #L##PVE# ",
"moonknight tierlist moonknight": "Moon Knight [Mr. Knight] #D##PVE##Energy#",
"moonstone tierlist moonstone": "Moonstone [Dark Avengers] #D##PVE##Energy#",
"morbius tierlist morbius": "Morbius [Modern] #D##PVE##P##Rage#",
"morganlefay tierlist morganlefay": "Morgan Le Fay [Modern] #PVE# ",
"msmarvelkamalakhan tierlist msmarvelkamalakhan": "Ms. Marvel Kamala Khan [Inhumans: Attilan Rising] #D##PVE##Authority#",
"mysterio tierlist mysterio": "Mysterio [Spider-Man: Far From Home] #D##PVE##Rage#",
"mystique tierlist mystique": "Mystique [Modern] #S##D##PVE##Cry##Rage#",
"namor tierlist namor": "Namor [Phoenix Five] #D##PVE##P##Rage#",
"nebula tierlist nebula": "Nebula [Avengers: Endgame] #PVE# ",
"negasonicteenagewarhead tierlist negasonicteenagewarhead": "Negasonic Teenage Warhead [Modern] #D##PVE##Cry##Rage#",
"nickfury tierlist nickfury": "Nick Fury [Captain Marvel] #L##S##PVE##P##Insight#",
"nightcrawler tierlist nightcrawler": "Nightcrawler [Classic] #D##PVE##Cra##Rage#",
"novarichardrider tierlist novarichardrider": "Nova Richard Rider [Modern] #L##S##D##PVE##Cry##Greed#",
"novasamalexander tierlist novasamalexander": "Nova Sam Alexander [All-New, All-Different] #D##PVP##Cra##Rage#",
"odin tierlist odin": "Odin [All-Father] #L##D##PVE##Cry##E##Rage#",
"philcoulson tierlist philcoulson": "Phil Coulson [A.O.S. Season 3] #S##PVE# ",
"phyla-vell tierlist phyla-vell": "Phyla-Vell [Modern] #S##PVE##Insight#",
"professorx tierlist professorx": "Professor X [Classic] #D##PVE##C##Rage#",
"proximamidnight tierlist proximamidnight": "Proxima Midnight [Dark Obsidian Armor] #L##PVE##C# ",
"psylocke tierlist psylocke": "Psylocke [Disassembled] #D##PVE##Cry##Rage#",
"punisher tierlist punisher": "Punisher [Cosmic Ghost Rider] #L##D##PVE##Rage#",
"quasaravrilkincaid tierlist quasaravrilkincaid": "Quasar Avril Kincaid [All-New, All-Different] #PVE# ",
"quicksilver tierlist quicksilver": "Quicksilver [Uncanny Avengers] #D##PVP##C##Rage#",
"rachelsummers tierlist rachelsummers": "Rachel Summers [Modern] #D##PVE##Cry# ",
"redguardian tierlist redguardian": "Red Guardian [Black Widow] #D##PVE##Rage#",
"redhulk tierlist redhulk": "Red Hulk [Symbiote of Vengeance] #L##D##PVE# ",
"redshe-hulk tierlist redshe-hulk": "Red She-Hulk [Modern] #L##S##D##PVE##P##Rage#",
"redskull tierlist redskull": "Red Skull [Hydra Armor] #D##PVE##Rage#",
"rescue tierlist rescue": "Rescue [Avengers: Endgame] #PVE# ",
"rhino tierlist rhino": "Rhino [Classic] #L##PVE# ",
"rocketraccoon tierlist rocketraccoon": "Rocket Raccoon [Avengers: Endgame] #PVE# ",
"rogue tierlist rogue": "Rogue [Excalibur] #D##PVE##Judgement#",
"ronan tierlist ronan": "Ronan [Captain Marvel] #L##S##PVE# ",
"sabretooth tierlist sabretooth": "Sabretooth [Uncanny Avengers] #D##PVE# ",
"sandman tierlist sandman": "Sandman [Classic] #PVE# ",
"satana tierlist satana": "Satana [Marvel Legacy] #L##PVE# ",
"scarletspider tierlist scarletspider": "Scarlet Spider [Modern] #S##D##PVE##Energy#",
"scarletwitch tierlist scarletwitch": "Scarlet Witch [WandaVision] #L##D##PVE##E##Rage#",
"scorpion tierlist scorpion": "Scorpion [Modern] #D##PVE# ",
"scream tierlist scream": "Scream [Modern] #PVE##Energy#",
"sentinel tierlist sentinel": "Sentinel [Nimrod the Lesser] #L##D##PVE##P##Regen#",
"sentry tierlist sentry": "Sentry [Modern] #L##D##PVP##Lu##Regen#",
"sersi tierlist sersi": "Sersi [Modern] #S##PVE# ",
"shadowshell tierlist shadowshell": "Shadow Shell [Modern] #PVE##PVP##Insight#",
"shang-chi tierlist shang-chi": "Shang-Chi [Modern] #PVE# ",
"she-hulk tierlist she-hulk": "She-Hulk [Avengers] #S##PVE##Insight#",
"shuri tierlist shuri": "Shuri [Black Panther] #S##PVE##Insight#",
"sif tierlist sif": "Sif [Modern] #PVE# ",
"silk tierlist silk": "Silk [Web Suit] #PVE# ",
"silversurfer tierlist silversurfer": "Silver Surfer [Black] #L##D##PVP##E##Regen#",
"sin tierlist sin": "Sin [All-New, All-Different] #PVE# ",
"singularity tierlist singularity": "Singularity [Secret Wars: A-Force] #PVE# ",
"sistergrimm tierlist sistergrimm": "Sister Grimm [All-New, All-Different] #PVE# ",
"skurge tierlist skurge": "Skurge [ Thor: Ragnarok] #PVE# ",
"slapstick tierlist slapstick": "Slapstick [Modern] #D##PVE##P##Rage#",
"songbird tierlist songbird": "Songbird [New Avengers] #PVE# ",
"spider-gwen tierlist spider-gwen": "Spider-Gwen [Gwenom] #D##PVE##Rage#",
"spider-man tierlist spider-man": "Spider-Man [Spider-Man: Far From Home] #D##PVE##PVP##Rage#",
"spider-man2099 tierlist spider-man2099": "Spider-Man 2099 [All-New, All-Different] #L##D##PVE##P##Rage#",
"spider-manmilesmorales tierlist spider-manmilesmorales": "Spider-Man Miles Morales [Absolute Carnage] #L##D##PVE##Rage#",
"spider-woman tierlist spider-woman": "Spider-Woman [Modern] #L##D##PVE##P##Rage#",
"squirrelgirl tierlist squirrelgirl": "Squirrel Girl [Marvel NOW!] #PVE# ",
"star-lord tierlist star-lord": "Star-Lord [Grounded] #L##D##PVE##Rage#",
"storm tierlist storm": "Storm [Inhumans vs X-Men] #D##PVE##Rage#",
"stryfe tierlist stryfe": "Stryfe [Modern] #L##D##PVE##P##E##Regen#",
"sunbird tierlist sunbird": "Sun Bird [Modern] #S##D##PVE##PVP##P##Regen#",
"supergiant tierlist supergiant": "Supergiant [Dark Obsidian Armor] #L##PVE##C# ",
"swordmaster tierlist swordmaster": "Sword Master [Modern] #PVE# ",
"taskmaster tierlist taskmaster": "Taskmaster [Black Widow] #S##PVE##Insight#",
"thane tierlist thane": "Thane [Modern] #L##D##PVE##P##Authority#",
"thanos tierlist thanos": "Thanos [Avengers: Endgame] #L##D##PVP##E##Regen#",
"thething tierlist thething": "The Thing [Classic] #S##D##PVE##Insight#",
"thor tierlist thor": "Thor [Herald of Thunder] #D##PVE##Rage#",
"thorjanefoster tierlist thorjanefoster": "Thor Jane Foster [All-New, All-Different] #PVE# ",
"titania tierlist titania": "Titania [Modern] #L##PVE# ",
"ulik tierlist ulik": "Ulik [Modern] #PVE# ",
"ultron tierlist ultron": "Ultron [Avengers: Age of Ultra] #PVE# ",
"ulyssesklaue tierlist ulyssesklaue": "Ulysses Klaue [ Black Panther] #S##PVE# ",
"valkyrie tierlist valkyrie": "Valkyrie [Fearless Defenders] #S##PVE##P##Insight#",
"venom tierlist venom": "Venom [War of the Realms] #S##D##PVE##Rage#",
"victorious tierlist victorious": "Victorious [Modern] #L##Regen#",
"viper tierlist viper": "Viper [Modern] #L##PVE##Rage#",
"vision tierlist vision": "Vision [WandaVision] #L##D##PVE##Rage#",
"volstagg tierlist volstagg": "Volstagg [Modern] #S##PVE# ",
"vulture tierlist vulture": "Vulture [Spider-Man: Homecoming] #PVE# ",
"warmachine tierlist warmachine": "War Machine [Avengers: Endgame] #PVE# ",
"wartiger tierlist wartiger": "War Tiger [Modern] #PVE##PVP##Regen#",
"warpath tierlist warpath": "Warpath [X-Force] #PVE# ",
"warwolf tierlist warwolf": "Warwolf [The Howling Commandos of S.H.I.E.L.D.] #L##S##PVE# ",
"wasp tierlist wasp": "Wasp [Ant-Man and the Wasp] #L##S##PVP# ",
"waspnadiavandyne tierlist waspnadiavandyne": "Wasp Nadia Van Dyne [Modern] #PVE##P# ",
"wave tierlist wave": "Wave [Modern] #S##PVE##Cry# ",
"weaponhex tierlist weaponhex": "Weapon Hex [Infinity Warps] #S##PVE##P# ",
"whiplash tierlist whiplash": "Whiplash [ Iron Man 2] #PVE# ",
"whitefox tierlist whitefox": "White Fox [Lifestyle Series 2] #L##S##PVE##Cry##Insight#",
"whitetiger tierlist whitetiger": "White Tiger [New Avengers] #PVE# ",
"wiccan tierlist wiccan": "Wiccan [New Avengers] #L##S##PVE# ",
"wintersoldier tierlist wintersoldier": "Winter Soldier [Avengers: Infinity War] #D##PVP##Rage#",
"wolverine tierlist wolverine": "Wolverine [House of X] #D##PVE##PVP##Regen#",
"wong tierlist wong": "Wong [Doctor Strange] #PVE# ",
"x-23 tierlist x-23": "X-23 [All-New Wolverine] #D##PVE##Cra##Rage#",
"yelenabelova tierlist yelenabelova": "Yelena Belova [Black Widow (Snow Suit)] #D##PVE##PVP##P##Rage#",
"yellowjacket tierlist yellowjacket": "Yellowjacket [Marvel NOW!] #PVE# ",
"yondu tierlist yondu": "Yondu [Guardians of the Galaxy 2] #PVE# ",

};
